language: node_js
install: npm install -g gitbook-cli
before_script: gitbook install
node_js:
- '0.10'
script: gitbook build
after_success:
- bash deploy.sh
# env:
#   global:
#     secure: btVtMDy4AgwWAX/l6qc5k+4aP5lPvIC6goxYr+5we21JRzIo66asBEeCxdfLqeW7BqzhARFHnPVQ02Q/2tRZm4QiCeAXgyq2U1+pxej/GT0yOrMBzPWMVvozWYAGMMYMY4GVIpqLm50BDDiWpKrwS0/aQpnq2NvMZEoA3BvdVfYKVW8mnWxZcIo95ICv5awzF4LMm1EeKqFzkf1ZREAcePGZ7PpHGUWBRYHcJLY+NIj0fevRjUhxasf2v/Pr2RjyUOjzuFLFbVTJ5gPbYtwh1Ziqlpd8bxN9Es+wL8SRgb8hbrJ5KhcyQ3EnWBNKS19yY8KaG0Q1B/SfYxdsnAmCa5fzlJlPv5Qx4hr2EPSYVLGCXE6UCA7fO75XVG1J1kFdeODUDHN59VuykJDpUxB2y8T7xZEhfieHanIaX5fSTX+UCGFY7m0lNjMVJkbnwafXM8YVGpL8e0XmgUiFAP8gfgvF0D606RclS/0sHAGJI+f+rp9+Zb5Swh0hVHuAh9A7+TmbBr1dwYCbLygjWCIxUOXSQxxXp270itxLfTBXRT9vQ0/uxCLvrr9STNRbIMX7sT5DLT85HzFQ1vDlTSpyEWAOvYCAJmd/ye9LL25ROTXwsy4xR3+KCiv+VeG79r29tdLPB2WE/lORRTGw8seP8ATXAsmvrGtBKxcNMc28GM8=
